### ISSUE TITLE
No comunication after baudrate is set

### ISSUE THREAD

**Issue by ghost** [positron96/cnc3018-offline-controller#4] opened 2022-01-09 11:58 UTC
Hardware:
-Offline Controller based on SMT32F (same as shown in the developer pictures)
-CNC Controller is woodpecker v3.3 with grbl firmware v1.1

What Works:
-Serial probing cycle for baudrate seems to work
-Controller shows interface,.
-All menu entries are shown and can be selected. 

What doesn't work:
-The only serial output from the offline controller is the $I sent in different baud rates to probe for the correct baud rate.

Test made:
-With a serial probe in tx rx terminals to check for comms, the behavior is as follows: 
-A few $I are sent by the offline controller in different baud rates. 
-The machine responses with  [VER:1.1f.20170801:] [OPT:V,15,128] ok
-The offline controller understands the response and stops sending any further comunication.

The offline controller only shows the machine as X idle or sometimes Lockpad Idle, but no further comand comes out of the offline controller, not with a SD card file, not with the DRO, or any other entry on the menu.

**Comment by positron96** [comment] 2022-01-10 06:54
Duplicate of #5

**Closed as completed by positron96** 2022-01-10 06:54 UTC
