### ISSUE TITLE
Impossible to flash GD32F103C8T6 chip

### ISSUE THREAD

**Issue by TWill974** [positron96/cnc3018-offline-controller#7] opened 2022-03-30 18:14 UTC
Hi,

When i flash the .hex firmware with  a st link usb key v2, all seems to be OK but at the verification step , i have this error :  Programming error @ 0x08010000!

Is it due to the problem of short memory of the GD32F103C8T6 chip ?

Do you have the same firmware but lighter ?

**Comment by positron96** [comment] 2022-04-04 08:00
Hi. I believe this is a duplicate of #6 and yes, AFAIK GD chip has really 64k, and the firmware is larger than 64k. Actually I tried to keep it under 64k before giving up, so if I roll back some months of commits, I might get a sub-64k firmware. It will lack features though.

**Closed as completed by positron96** 2022-04-04 08:00 UTC

**Comment by TWill974** [comment] 2022-04-09 06:46
Hi,
OK i understand...If you can try to delete, the less interesting features ...But the best will be to have a light firmware with all features.... :-)  Please, let me know, when you will generate the light firmware < 64k

Thanks a lot.
