### ISSUE TITLE
can this fit on the c8 version of the chip?

### ISSUE THREAD

**Issue by revjmoney** [positron96/cnc3018-offline-controller#21] opened 2024-07-24 07:17 UTC
i screwed up and flashed this firmware to my controller without looking at the chip first and mine has the c8 variant of the chip and platformio says it's 12000 bytes too big.  my controller is bricked for now unless i can figure out how to fit this?  maybe take out stuff?  all i need is jog and dro really.  i wish i had enough coding skills to fix this!  thanks for your time anyways!

**Comment by revjmoney** [comment] 2024-07-24 07:40
so i realized i may be missing something but my stlink wont program this and my thingy is bricked.

**Comment by revjmoney** [comment] 2024-07-24 08:03
ok, i have a gd32f103c8t6 on my board.  idk what this means, i just want the thing to turn back on. :)

**Comment by positron96** [comment] 2024-07-25 16:46
Hi. So this is a duplicate of #7 and unfortunately only original STM32 C8T6s have 128k, chinese copies like GD32 or APM32 have 64k. You can reflash the original firmware, the one from my machine is in README

**Closed as completed by positron96** 2024-07-25 16:46 UTC
Labels: duplicate, question

**Comment by revjmoney** [comment] 2024-07-25 20:07
i also could not burn your original firmware file... i found another on here (github) somewhere that worked! ty
